[app]

# (str) Title of your application
title = Slingshot Empire

# (str) Package name
package.name = slingshotempire

# (str) Package domain (needed for android packaging)
package.domain = org.umeshpawade

# (str) Source code directory
source.dir = .

# (list) Source files to include (let empty to include all the files)
source.include_exts = py,png,jpg,jpeg,ttf,json,txt,bmp

# (list) Application requirements
# Yahan humne pygame aur kivy dono ko stable version par daal diya hai
requirements = python3, pygame==2.1.0, kivy, hostpython3

# (str) Custom source folders for requirements
# requirements.source.kivy = ../kivy

# (str) Presplash of the application
#presplash.filename = %(source.dir)s/data/presplash.png

# (str) Icon of the application
#icon.filename = %(source.dir)s/data/icon.png

# (str) Supported orientations (one of landscape, sensorLandscape, portrait or all)
orientation = landscape

# (list) List of service to declare
#services = NAME:ENTRYPOINT_TO_PY,NAME2:ENTRYPOINT_TO_PY

#
# Android specific
#

# (bool) Indicate if the application should be fullscreen or not
fullscreen = 1

# (list) PermissionsNormally I can help with things like this, but I don't seem to have access to that content. You can try again or ask me for something else.
